approximation.o: approximation.c approximation.h \
 /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h sys_lin.h \
 /home/romane/NE-2.5/TPMG/../OBJETS/u_xt_interface.h \
 /home/romane/NE-2.5/TPMG/../OBJETS/o_interface.h
bezier.o: bezier.c bezier.h /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h
figure.o: figure.c /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h
nurbs.o: nurbs.c nurbs.h /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h
o_approximation.o: o_approximation.c \
 /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h approximation.h \
 sys_lin.h /home/romane/NE-2.5/TPMG/../OBJETS/u_xt_interface.h \
 /home/romane/NE-2.5/TPMG/../OBJETS/o_interface.h bezier.h
o_bezier.o: o_bezier.c /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h bezier.h
o_cerc.o: o_cerc.c /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../OBJETS/u_table.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h figure.h
o_nurbs.o: o_nurbs.c /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h nurbs.h
o_sph.o: o_sph.c /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h figure.h
o_surface_bezier.o: o_surface_bezier.c \
 /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h surface_bezier.h \
 bezier.h
surface_bezier.o: surface_bezier.c surface_bezier.h \
 /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h bezier.h
sys_lin.o: sys_lin.c sys_lin.h \
 /home/romane/NE-2.5/TPMG/../OBJETS/u_xt_interface.h \
 /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../OBJETS/o_interface.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h
