figure.o: figure.c /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h
o_cerc.o: o_cerc.c /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../OBJETS/u_table.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h figure.h
o_sph.o: o_sph.c /home/romane/NE-2.5/TPMG/../COEUR/o_objet.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/eprintf.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec_base.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_geometrie.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/codec.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/l_liste.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_memoire.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_widget.h \
 /home/romane/NE-2.5/TPMG/../UTILITAIRES/u_etat.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_base.h \
 /home/romane/NE-2.5/TPMG/../TYPES/t_geometrie.h figure.h
